#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────
#
# provision-stage.sh <dev|prod>
#
# Walks the dashboards that "Provision the dev database, the Cloudflare API
# token and the stage secrets" (#36) lists, validates every value live, and
# writes it to `.env.<stage>` (gitignored) and to the GitHub Actions
# environment of the same name (secrets for secret values, variables for the
# rest), so the deploy jobs in #37 read the same names as `.env.example`.
# Run it for `dev` first, then `prod`: values that are shared (the API token,
# the service keys) are offered for reuse from the other stage's file.

STAGE="${1:-}"
START_STAGE=1
case "$STAGE" in
  dev|prod) ;;
  *) printf 'usage: %s <dev|prod> [--from N]\n' "$0" >&2; exit 2 ;;
esac
if [[ "${2:-}" == "--from" && "${3:-}" =~ ^[0-9]+$ ]]; then START_STAGE="$3"; fi
OTHER_STAGE=$([[ "$STAGE" == dev ]] && echo prod || echo dev)
ENV_FILE=".env.$STAGE"
SIBLING_ENV=".env.$OTHER_STAGE"

ACCOUNT_ID="3056ba6cc5916b47fece5b044c6a8434"          # NP Brands
HOST_ZONE="npbrands.au"          # Worker hostnames, Workers Routes and DNS live here
MAIL_DOMAIN="npbrands.com.au"   # Postmark sender and the sign-in allowlist
DB_NAME=$([[ "$STAGE" == dev ]] && echo digital-shelf-dev || echo digital-shelf)
PROD_HYPERDRIVE_ID="dba7756cd8844f54b6a5fc2fe8bfbed0"   # recorded on #25
GATEWAY_NAME="digital-shelf-ai-gateway-$STAGE"
# Axiom allows three datasets on this plan, so both stages share two and the
# stage is the OTel resource attribute deployment.environment.name (2026-09-10).
TRACES_DATASET="digital-shelf-traces"
LOGS_DATASET="digital-shelf-logs"
# The Axiom organisation this project reports to (the team org "npbrands"; a
# personal org with the same display name exists, so the id is what counts).
AXIOM_ORG_ID="${AXIOM_ORG_ID:-npbrands-etkr}"
AXIOM_APP="https://app.axiom.co/$AXIOM_ORG_ID"
# The axiom CLI is used for dataset creation only when one of its logins
# (~/.axiom.toml deployments) is for that org; otherwise the dashboard does it.
AXIOM_CLI_DEPLOYMENT=$(awk -v org="$AXIOM_ORG_ID" '
  $0 ~ /^\s*\[deployments\./ { dep = $1; sub(/^\[deployments\./, "", dep); sub(/\]$/, "", dep) }
  $1 == "org_id" { gsub(/"/, "", $3); if ($3 == org) { print dep; exit } }' "$HOME/.axiom.toml" 2>/dev/null || true)
CF_API="https://api.cloudflare.com/client/v4"
GH_REPO=""

# ── helpers specific to this wizard (the library above stays untouched) ────

# open_url, redefined: on WSL, explorer.exe opens the default browser but
# exits non-zero, which the library reads as a failure. Same behaviour
# elsewhere.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  if command -v wslview >/dev/null 2>&1; then wslview "$url" >/dev/null 2>&1 || true
  elif command -v powershell.exe >/dev/null 2>&1; then powershell.exe -NoProfile -Command "Start-Process '$url'" >/dev/null 2>&1 || true
  elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url" >/dev/null 2>&1 || true
  elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url" >/dev/null 2>&1 || true
  elif command -v open >/dev/null 2>&1; then open "$url" >/dev/null 2>&1 || true
  else warn "couldn't open a browser; visit it manually: $url"
  fi
  note "(if no tab appeared, open that URL yourself)"
}

# _sibling KEY: the other stage's saved value for KEY, if any.
_sibling() {
  [[ -f "$SIBLING_ENV" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$SIBLING_ENV" | tail -n1) || return 1
  [[ -n "${line#*=}" ]] || return 1
  printf '%s' "${line#*=}"
}

# reuse_or_ask[_secret] KEY "Prompt": like ask/ask_secret, but when this
# stage has no value yet and the other stage does, offers to reuse it.
reuse_or_ask_secret() {
  local key="$1" prompt="$2" sib
  if [[ -z "$(_existing "$key" || true)" ]] && sib=$(_sibling "$key"); then
    if confirm "Reuse the $key already saved in $SIBLING_ENV?"; then
      printf -v "$key" '%s' "$sib"; return
    fi
  fi
  ask_secret "$key" "$prompt"
}
reuse_or_ask() {
  local key="$1" prompt="$2" sib
  if [[ -z "$(_existing "$key" || true)" ]] && sib=$(_sibling "$key"); then
    if confirm "Reuse the $key already saved in $SIBLING_ENV ($sib)?"; then
      printf -v "$key" '%s' "$sib"; return
    fi
  fi
  ask "$key" "$prompt"
}

# set_env_secret NAME VALUE: GitHub Actions *environment* secret for $STAGE.
set_env_secret() {
  local name="$1" value="$2"
  if [[ -n "$GH_REPO" ]] && printf '%s' "$value" | gh secret set "$name" --env "$STAGE" --repo "$GH_REPO" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$STAGE/$name")
    printf '  %s✓ set%s GitHub environment secret %s/%s\n' "$GREEN" "$RESET" "$STAGE" "$name"
  else
    SKIPPED+=("GitHub environment secret $STAGE/$name (gh secret set $name --env $STAGE)")
    warn "skipped GitHub secret $STAGE/$name; set it later"
  fi
}
# set_env_var NAME VALUE: GitHub Actions *environment* variable for $STAGE.
set_env_var() {
  local name="$1" value="$2"
  if [[ -n "$GH_REPO" ]] && gh variable set "$name" --env "$STAGE" --repo "$GH_REPO" --body "$value" >/dev/null 2>&1; then
    printf '  %s✓ set%s GitHub environment variable %s/%s\n' "$GREEN" "$RESET" "$STAGE" "$name"
  else
    SKIPPED+=("GitHub environment variable $STAGE/$name (gh variable set $name --env $STAGE)")
    warn "skipped GitHub variable $STAGE/$name; set it later"
  fi
}
# ask_default KEY "Prompt" DEFAULT: ask, and fall back to DEFAULT on Enter
# when no earlier value exists.
ask_default() {
  local key="$1" prompt="$2" def="$3"
  ask "$key" "$prompt [$def]:"
  [[ -n "${!key}" ]] || printf -v "$key" '%s' "$def"
}
# save_secret KEY VALUE / save_var KEY VALUE: env file + GitHub, in one go.
save_secret() { write_env "$1" "$2"; set_env_secret "$1" "$2"; }
save_var()    { write_env "$1" "$2"; set_env_var "$1" "$2"; }

# cf GET|POST PATH [JSON]: call the Cloudflare API with CLOUDFLARE_API_TOKEN.
cf() {
  local method="$1" path="$2" body="${3:-}"
  if [[ -n "$body" ]]; then
    curl -sS -X "$method" "$CF_API$path" -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
      -H 'Content-Type: application/json' --data "$body" || printf '{"success":false,"errors":[{"message":"curl failed"}]}'
  else
    curl -sS -X "$method" "$CF_API$path" -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" || printf '{"success":false,"errors":[{"message":"curl failed"}]}'
  fi
}
# cf_ok JSON: succeeds when the API answered success:true; prints errors otherwise.
cf_ok() {
  if [[ "$(printf '%s' "$1" | jq -r '.success // false')" == "true" ]]; then return 0; fi
  warn "Cloudflare API said: $(printf '%s' "$1" | jq -r '[.errors[]?.message] | join("; ")' 2>/dev/null || printf '%s' "$1" | head -c 300)"
  return 1
}

# verify_cf_token VALUE: tokens/verify; prints the token id and status.
verify_cf_token() {
  local out
  out=$(curl -sS "$CF_API/user/tokens/verify" -H "Authorization: Bearer $1" || true)
  if [[ "$(printf '%s' "$out" | jq -r '.success // false')" == "true" && "$(printf '%s' "$out" | jq -r '.result.status')" == "active" ]]; then
    say "${GREEN}✓${RESET} token $(printf '%s' "$out" | jq -r '.result.id') is active"
    return 0
  fi
  warn "token did not verify: $(printf '%s' "$out" | jq -r '[.errors[]?.message] | join("; ")' 2>/dev/null)"
  return 1
}

# normalise_database_url URL: PlanetScale's generated string, made safe for
# psql, drizzle-kit (node `pg`) and Alchemy's Hyperdrive origin at once.
normalise_database_url() {
  local url="$1"
  url="${url/postgresql:\/\//postgres://}"
  url=$(printf '%s' "$url" | sed -E 's/[?&]sslrootcert=[^&]*//; s/[?&]sslnegotiation=[^&]*//')   # `pg` reads sslrootcert as a file path
  url=$(printf '%s' "$url" | sed -E 's/&+/\&/g; s/\?&/?/; s/[?&]$//')
  if [[ "$url" == *:6432/* ]]; then warn "port 6432 is PgBouncer; Hyperdrive and migrations need 5432, rewriting"; url="${url/:6432\//:5432/}"; fi
  if [[ "$url" != *sslmode=* ]]; then
    if [[ "$url" == *\?* ]]; then url="$url&sslmode=verify-full"; else url="$url?sslmode=verify-full"; fi
  fi
  printf '%s' "$url"
}

# ── the wizard ───────────────────────────────────────────────────────────

TOTAL_STAGES=10

banner "Digital Shelf · provision the $STAGE stage"

# ── 1 · preflight ─────────────────────────────────────────────────────────
stage_1() {
stage "Preflight: tools, GitHub environment, stage constants"
missing=()
for tool in gh curl jq psql openssl axiom; do command -v "$tool" >/dev/null 2>&1 || missing+=("$tool"); done
if (( ${#missing[@]} )); then warn "missing tools: ${missing[*]} (brew install them, then re-run)"; exit 1; fi
if gh auth status >/dev/null 2>&1; then
  GH_REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true)
fi
if [[ -z "$GH_REPO" ]]; then
  warn "gh is not authenticated for this repo; GitHub secrets will be skipped (run gh auth login and re-run to fill them)"
else
  say "GitHub repo: $GH_REPO"
  if gh api --method PUT "repos/$GH_REPO/environments/$STAGE" >/dev/null 2>&1; then
    say "${GREEN}✓${RESET} GitHub Actions environment '$STAGE' exists"
  else
    warn "could not create the GitHub Actions environment '$STAGE'; secrets will be skipped"; GH_REPO=""
  fi
fi
say "Values land in $ENV_FILE (gitignored) and in the GitHub environment '$STAGE'."
save_var CLOUDFLARE_ACCOUNT_ID "$ACCOUNT_ID"
save_var AI_GATEWAY_ACCOUNT_ID "$ACCOUNT_ID"
save_var AI_GATEWAY_ID "$GATEWAY_NAME"
pause
}

# ── 2 · Cloudflare API token for Alchemy ──────────────────────────────────
stage_2() {
stage "Cloudflare: the scoped API token Alchemy deploys with"
say "One custom token, shared by both stages, used locally and by the deploy jobs."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → Custom token (Get started) → name it 'digital-shelf alchemy'."
step "Permissions (add a row for each):"
note "    Account · Workers Scripts · Edit        (Workers, Workflows, custom domains, the Alchemy state Worker)"
note "    Account · Hyperdrive · Edit"
note "    Account · Workers R2 Storage · Edit"
note "    Account · AI Gateway · Edit"
note "    Account · Browser Rendering · Edit"
note "    Account · Secrets Store · Edit          (Alchemy's state store keeps its token there)"
note "    Account · Account Settings · Read"
note "    Zone · Workers Routes · Edit"
note "    Zone · DNS · Edit"
note "    Zone · Zone · Read                      (Alchemy looks the zone up by name)"
step "Account Resources: Include → NP Brands only. Zone Resources: Include → Specific zone → $HOST_ZONE."
step "No client IP filter, no TTL. Continue to summary → Create Token → copy it (shown once)."
note "If the Browser Rendering or Secrets Store rows are not offered under those names, note the name shown and tell the ticket."
reuse_or_ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"
until verify_cf_token "$CLOUDFLARE_API_TOKEN"; do ask_secret CLOUDFLARE_API_TOKEN "Paste the API token again:"; done
out=$(cf GET "/accounts/$ACCOUNT_ID/hyperdrive/configs")
if cf_ok "$out"; then
  say "${GREEN}✓${RESET} Hyperdrive scope works: $(printf '%s' "$out" | jq -r '[.result[].name] | join(", ")')"
else
  warn "the token cannot list Hyperdrive configs; check the Hyperdrive · Edit row"
fi
out=$(cf GET "/accounts/$ACCOUNT_ID/workers/subdomain")
WORKERS_SUBDOMAIN=""
if cf_ok "$out"; then
  WORKERS_SUBDOMAIN=$(printf '%s' "$out" | jq -r '.result.subdomain // empty')
  say "${GREEN}✓${RESET} Workers scope works; workers.dev subdomain: ${WORKERS_SUBDOMAIN:-<none enabled>}"
  [[ -n "$WORKERS_SUBDOMAIN" ]] || warn "Alchemy's state store needs workers.dev enabled on the account (Workers & Pages → your subdomain)"
else
  warn "the token cannot read the Workers subdomain; check the Workers Scripts · Edit row"
fi
save_secret CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"
if [[ "$STAGE" == dev ]]; then
  SERVER_HOSTNAME="shelf-dev.apps.$HOST_ZONE"
else
  SERVER_HOSTNAME="digital-shelf-server-prod.${WORKERS_SUBDOMAIN:-<subdomain>}.workers.dev"
  note "prod stays on workers.dev until the cutover sets shelf.apps.$HOST_ZONE (ADR 0006)."
fi
ask_default SERVER_HOSTNAME "Hostname for the $STAGE Worker" "$SERVER_HOSTNAME"
save_var SERVER_HOSTNAME "$SERVER_HOSTNAME"
pause
}

# ── 3 · the PlanetScale database and its Hyperdrive config ────────────────
stage_3() {
stage "PlanetScale: the $STAGE database ($DB_NAME) and its Hyperdrive config"
if [[ "$STAGE" == dev ]]; then
  say "Create the dev database through the Cloudflare-linked flow, like 'digital-shelf' was."
  open_url "https://dash.cloudflare.com/?to=/:account/workers/hyperdrive?modal=1&type=planetscale&step=1"
  step "In the PlanetScale modal: name '$DB_NAME', PostgreSQL, region matching prod (aws-ap-southeast-2 / Sydney) if a region is offered."
  step "Finish the flow; it creates the database in the PlanetScale org and a Hyperdrive config named '$DB_NAME'."
  pause "Done? Press Enter and the wizard will look the config up."
fi
HYPERDRIVE_CONFIG_ID=""; HYPERDRIVE_HOST=""
while :; do
  out=$(cf GET "/accounts/$ACCOUNT_ID/hyperdrive/configs")
  cfg=$(printf '%s' "$out" | jq -c --arg n "$DB_NAME" '.result[]? | select(.name == $n)' | head -n1)
  if [[ -n "$cfg" ]]; then
    HYPERDRIVE_CONFIG_ID=$(printf '%s' "$cfg" | jq -r .id)
    HYPERDRIVE_HOST=$(printf '%s' "$cfg" | jq -r .origin.host)
    say "${GREEN}✓${RESET} Hyperdrive config '$DB_NAME': id $HYPERDRIVE_CONFIG_ID"
    note "    origin $(printf '%s' "$cfg" | jq -r '"\(.origin.host):\(.origin.port) db=\(.origin.database) user=\(.origin.user)"')"
    note "    integration $(printf '%s' "$cfg" | jq -r '.origin.integration_name // "none"'), caching disabled: $(printf '%s' "$cfg" | jq -r '.caching.disabled // false') (Alchemy turns it off on adoption)"
    if [[ "$STAGE" == prod && "$HYPERDRIVE_CONFIG_ID" != "$PROD_HYPERDRIVE_ID" ]]; then
      warn "expected the prod config id $PROD_HYPERDRIVE_ID (from #25) but found $HYPERDRIVE_CONFIG_ID; record this on the ticket"
    fi
    break
  fi
  warn "no Hyperdrive config named '$DB_NAME' on the account yet"
  confirm "Look again?" || break
done
[[ -n "$HYPERDRIVE_CONFIG_ID" ]] && save_var HYPERDRIVE_CONFIG_ID "$HYPERDRIVE_CONFIG_ID"
pause
}

# ── 4 · PlanetScale credentials → DATABASE_URL ────────────────────────────
stage_4() {
stage "PlanetScale: direct credentials for $DB_NAME (DATABASE_URL)"
say "Migrations run over this string, and Alchemy adopts the Hyperdrive config with it as the origin."
open_url "https://app.planetscale.com/"
step "Open the '$DB_NAME' database → Connect (top right) → branch 'main'."
step "Create default role (role 'postgres') → in 'How are you connecting?' pick a plain connection string."
step "Copy the whole postgresql://postgres.<branch_id>:pscale_pw_...@<host>:5432/postgres?... string. The password shows once."
reuse_or_ask_secret DATABASE_URL "Paste the connection string:"
while :; do
  DATABASE_URL=$(normalise_database_url "$DATABASE_URL")
  if [[ -n "$HYPERDRIVE_HOST" && "$DATABASE_URL" != *"@$HYPERDRIVE_HOST:"* ]]; then
    warn "host in the string differs from the Hyperdrive origin ($HYPERDRIVE_HOST); double-check you copied the $DB_NAME database"
  fi
  say "Checking SELECT 1 over the direct connection…"
  if version=$(PGSSLROOTCERT=system PGCONNECT_TIMEOUT=15 psql "$DATABASE_URL" -Atc 'select version()' 2>/tmp/provision-psql.err); then
    say "${GREEN}✓${RESET} connected: ${version%% on *}"
    # Migrations need DDL: prove it with a CREATE TABLE that is rolled back.
    if PGSSLROOTCERT=system psql "$DATABASE_URL" -Atc 'begin; create table _provision_probe(x int); rollback;' >/dev/null 2>/tmp/provision-psql.err; then
      say "${GREEN}✓${RESET} the role can run DDL (rolled-back CREATE TABLE), so pnpm db:migrate will work"
      break
    fi
    warn "the role cannot run DDL: $(head -c 200 /tmp/provision-psql.err). Migrations need the default 'postgres' role or one with CREATE on the schema; create that role and paste its string."
  else
    warn "psql failed: $(head -c 300 /tmp/provision-psql.err)"
    note "psql needs libpq 16+ for sslrootcert=system; on an older libpq, try again after 'brew install libpq'."
  fi
  confirm "Paste the string again?" || break
  ask_secret DATABASE_URL "Paste the connection string:"
done
save_secret DATABASE_URL "$DATABASE_URL"
pause
}

# ── 5 · Better Auth ───────────────────────────────────────────────────────
stage_5() {
stage "Better Auth: secret, base URL, allowed e-mail domains"
AUTH_SECRET=$(_existing AUTH_SECRET || true)
if [[ -z "$AUTH_SECRET" ]]; then
  AUTH_SECRET=$(openssl rand -base64 32)
  say "${GREEN}✓${RESET} generated a fresh AUTH_SECRET for $STAGE (openssl rand -base64 32); never shared between stages"
else
  say "keeping the AUTH_SECRET already saved for $STAGE"
fi
save_secret AUTH_SECRET "$AUTH_SECRET"
save_var AUTH_BASE_URL "https://$SERVER_HOSTNAME"
AUTH_ALLOWED_EMAIL_DOMAINS=$(_existing AUTH_ALLOWED_EMAIL_DOMAINS || echo "$MAIL_DOMAIN")
ask_default AUTH_ALLOWED_EMAIL_DOMAINS "Allowed sign-in e-mail domains, comma-separated" "$AUTH_ALLOWED_EMAIL_DOMAINS"
save_var AUTH_ALLOWED_EMAIL_DOMAINS "$AUTH_ALLOWED_EMAIL_DOMAINS"
pause
}

# ── 6 · Postmark ──────────────────────────────────────────────────────────
stage_6() {
stage "Postmark: server token for the magic-link mail"
open_url "https://account.postmarkapp.com/servers"
step "Open the server that sends from $MAIL_DOMAIN (the sender signature or domain must be verified there)."
step "API Tokens tab → copy a Server API token (create one if the list is empty)."
reuse_or_ask_secret POSTMARK_SERVER_TOKEN "Paste the server token:"
while :; do
  out=$(curl -sS https://api.postmarkapp.com/server -H 'Accept: application/json' -H "X-Postmark-Server-Token: $POSTMARK_SERVER_TOKEN" || true)
  if name=$(printf '%s' "$out" | jq -er '.Name' 2>/dev/null); then say "${GREEN}✓${RESET} token belongs to server '$name'"; break; fi
  warn "Postmark rejected the token: $(printf '%s' "$out" | jq -r '.Message // .' 2>/dev/null | head -c 200)"
  confirm "Paste it again?" || break
  ask_secret POSTMARK_SERVER_TOKEN "Paste the server token:"
done
save_secret POSTMARK_SERVER_TOKEN "$POSTMARK_SERVER_TOKEN"
reuse_or_ask POSTMARK_FROM "From address on $MAIL_DOMAIN (a verified sender, e.g. shelf@$MAIL_DOMAIN):"
save_var POSTMARK_FROM "$POSTMARK_FROM"
POSTMARK_MESSAGE_STREAM=$(_existing POSTMARK_MESSAGE_STREAM || echo outbound)
ask_default POSTMARK_MESSAGE_STREAM "Message stream" "$POSTMARK_MESSAGE_STREAM"
save_var POSTMARK_MESSAGE_STREAM "$POSTMARK_MESSAGE_STREAM"
pause
}

# ── 7 · Scrappey ──────────────────────────────────────────────────────────
stage_7() {
stage "Scrappey: API key"
open_url "https://app.scrappey.com/"
step "On the Overview page, the 'API Key' card → Copy."
reuse_or_ask_secret SCRAPPEY_API_KEY "Paste the Scrappey API key:"
while :; do
  out=$(curl -sS "https://publisher.scrappey.com/api/v1/balance?key=$SCRAPPEY_API_KEY" || true)
  if bal=$(printf '%s' "$out" | jq -er '.balance' 2>/dev/null); then say "${GREEN}✓${RESET} key accepted; remaining balance: $bal requests"; break; fi
  warn "Scrappey did not return a balance: $(printf '%s' "$out" | head -c 200)"
  confirm "Paste it again?" || break
  ask_secret SCRAPPEY_API_KEY "Paste the Scrappey API key:"
done
save_secret SCRAPPEY_API_KEY "$SCRAPPEY_API_KEY"
pause
}

# ── 8 · AI Gateway token (Workers AI) ─────────────────────────────────────
stage_8() {
stage "AI Gateway: the Workers AI token the extraction calls carry"
say "The Worker calls @cf models through gateway '$GATEWAY_NAME' with a Cloudflare API token."
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → Custom token → name 'digital-shelf workers-ai'."
step "Permission: Account · Workers AI · Read. Account Resources: NP Brands only. Create and copy."
note "If the inference check below is refused, edit the token and add Account · Workers AI · Edit (the Workers AI docs ask for both)."
reuse_or_ask_secret AI_GATEWAY_TOKEN "Paste the Workers AI token:"
while :; do
  if verify_cf_token "$AI_GATEWAY_TOKEN"; then
    say "Running one tiny inference to prove the scope…"
    out=$(curl -sS -X POST "$CF_API/accounts/$ACCOUNT_ID/ai/run/@cf/zai-org/glm-4.7-flash" \
      -H "Authorization: Bearer $AI_GATEWAY_TOKEN" -H 'Content-Type: application/json' \
      --data '{"messages":[{"role":"user","content":"Reply with the single word OK."}],"max_tokens":8}' || true)
    if [[ "$(printf '%s' "$out" | jq -r '.success // false')" == "true" ]]; then
      say "${GREEN}✓${RESET} Workers AI answered: $(printf '%s' "$out" | jq -r '.result.response // .result | tostring' | head -c 60)"
      break
    fi
    warn "Workers AI refused: $(printf '%s' "$out" | jq -r '[.errors[]?.message] | join("; ")' 2>/dev/null | head -c 200)"
  fi
  confirm "Paste the token again?" || break
  ask_secret AI_GATEWAY_TOKEN "Paste the Workers AI token:"
done
save_secret AI_GATEWAY_TOKEN "$AI_GATEWAY_TOKEN"
pause
}

# ── 9 · Axiom ─────────────────────────────────────────────────────────────
stage_9() {
stage "Axiom: edge domain, the two shared datasets, an ingest-only token for $STAGE"
say "Everything here targets Axiom org '$AXIOM_ORG_ID'; the org switcher (top left) must show that org, not a personal one with the same name."
open_url "$AXIOM_APP/settings/general"
step "Settings → General → 'Edge deployment' names the region; the base domain follows from it:"
note "    US East 1 (AWS)      →  us-east-1.aws.edge.axiom.co"
note "    EU Central 1 (AWS)   →  eu-central-1.aws.edge.axiom.co"
while :; do
  reuse_or_ask AXIOM_DOMAIN "Edge base domain (or the region name as shown):"
  AXIOM_DOMAIN="${AXIOM_DOMAIN#https://}"; AXIOM_DOMAIN="${AXIOM_DOMAIN%/}"
  case "$(printf '%s' "$AXIOM_DOMAIN" | tr '[:upper:]' '[:lower:]')" in
    "us east 1 (aws)"|"us-east-1"|"us east 1") AXIOM_DOMAIN="us-east-1.aws.edge.axiom.co" ;;
    "eu central 1 (aws)"|"eu-central-1"|"eu central 1") AXIOM_DOMAIN="eu-central-1.aws.edge.axiom.co" ;;
  esac
  [[ -n "$AXIOM_DOMAIN" ]] && break
  warn "the domain cannot be empty"
done
say "using edge domain $AXIOM_DOMAIN"
[[ "$AXIOM_DOMAIN" == *.edge.axiom.co ]] || warn "'$AXIOM_DOMAIN' is not an *.edge.axiom.co domain; api.axiom.co is the legacy US-only ingest host"
datasets_done=0
if [[ -n "$AXIOM_CLI_DEPLOYMENT" ]] && existing=$(axiom dataset list -D "$AXIOM_CLI_DEPLOYMENT" -f json 2>/dev/null | jq -r '.[].name'); then
  say "Creating datasets with the axiom CLI login '$AXIOM_CLI_DEPLOYMENT' (org $AXIOM_ORG_ID)…"
  datasets_done=1
  for ds in "$TRACES_DATASET" "$LOGS_DATASET"; do
    if grep -qx "$ds" <<<"$existing"; then say "${GREEN}✓${RESET} dataset $ds exists"
    elif axiom dataset create -D "$AXIOM_CLI_DEPLOYMENT" --no-spinner -n "$ds" -d "Digital Shelf ${ds#digital-shelf-}, all stages (deployment.environment.name tells them apart)" >/dev/null 2>&1; then say "${GREEN}✓${RESET} created dataset $ds"
    else warn "could not create $ds with the CLI"; datasets_done=0; fi
  done
fi
if (( ! datasets_done )); then
  note "The axiom CLI has no login for org $AXIOM_ORG_ID (its logins: $(awk '$0 ~ /^\s*\[deployments\./ {d=$1; sub(/^\[deployments\./,"",d); sub(/\]$/,"",d); printf "%s ", d}' "$HOME/.axiom.toml" 2>/dev/null)), so create the datasets in the dashboard."
  open_url "$AXIOM_APP/settings/datasets"
  step "Settings → Datasets and views → New dataset: name '$TRACES_DATASET', kind Events, default retention → Save."
  step "Again: name '$LOGS_DATASET', kind Events → Save."
  note "Both stages share these two (the plan allows three datasets); any old digital-shelf-*-dev datasets can be deleted."
fi
pause "Both datasets in place? Press Enter."
open_url "$AXIOM_APP/settings/api-tokens"
step "New API token → name 'digital-shelf-$STAGE' → Basic → Dataset access: only $TRACES_DATASET and $LOGS_DATASET (ingest) → Create → copy (shown once)."
note "One token per stage, both scoped to the same two datasets, so either can be revoked alone."
note "If those two datasets are not offered in the picker, the browser is in another org: switch orgs and refresh."
ask_secret AXIOM_TOKEN "Paste the Axiom token:"
axiom_ok=0
while :; do
  now=$(date -u +%Y-%m-%dT%H:%M:%SZ)
  out=$(curl -sS -X POST "https://$AXIOM_DOMAIN/v1/ingest/$LOGS_DATASET" -H "Authorization: Bearer $AXIOM_TOKEN" \
    -H 'Content-Type: application/json' --data "[{\"time\":\"$now\",\"data\":{\"message\":\"provision-stage smoke\",\"stage\":\"$STAGE\"}}]" || true)
  if [[ "$(printf '%s' "$out" | jq -r '.ingested // 0' 2>/dev/null)" == "1" ]]; then
    say "${GREEN}✓${RESET} ingested one smoke event into $LOGS_DATASET via $AXIOM_DOMAIN"; axiom_ok=1; break
  fi
  warn "ingest failed: $(printf '%s' "$out" | head -c 200)"
  confirm "Paste the token again?" || break
  ask_secret AXIOM_TOKEN "Paste the Axiom token:"
done
if (( axiom_ok )); then
  save_var AXIOM_DOMAIN "$AXIOM_DOMAIN"
  save_secret AXIOM_TOKEN "$AXIOM_TOKEN"
else
  warn "not saving AXIOM_DOMAIN or AXIOM_TOKEN: the ingest never succeeded. Re-run with --from 9 once fixed."
  SKIPPED+=("Axiom: AXIOM_DOMAIN and AXIOM_TOKEN for $STAGE (re-run: $0 $STAGE --from 9)")
fi
pause
}

# ── 10 · AI Gateway OpenTelemetry export ──────────────────────────────────
stage_10() {
stage "AI Gateway: OpenTelemetry export declared by deployment"
note "packages/infra/src/Resources/AiGateway.ts declares the exporter from AXIOM_DOMAIN and AXIOM_TOKEN."
note "No dashboard step is needed; deployment applies the declared configuration."
}

# ── run ─────────────────────────────────────────────────────────────────────
if (( START_STAGE > 1 )); then
  # Re-entering later: reload what earlier stages captured into this run.
  for key in CLOUDFLARE_API_TOKEN SERVER_HOSTNAME HYPERDRIVE_CONFIG_ID AXIOM_DOMAIN; do
    printf -v "$key" '%s' "$(_existing "$key" || true)"
  done
  HYPERDRIVE_HOST=""; WORKERS_SUBDOMAIN=""
  if gh auth status >/dev/null 2>&1; then GH_REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || true); fi
  _STAGE_INDEX=$((START_STAGE - 1))
fi
for n in $(seq "$START_STAGE" "$TOTAL_STAGES"); do "stage_$n"; done

finish
say "Record on #36: where each secret lives ($ENV_FILE + GitHub environment '$STAGE'),"
say "the $STAGE Hyperdrive config id ${HYPERDRIVE_CONFIG_ID:-<not found>}, and any surprise the checks above showed."
